# Generated by Django 5.2.17 on 2026-09-28 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanbanapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JiraIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jira_id', models.CharField(db_index=True, max_length=50)),
                ('jira_key', models.CharField(db_index=True, max_length=50)),
                ('summary', models.CharField(default='', max_length=1000)),
                ('description', models.TextField(blank=True, default='')),
                ('status_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('status_key', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('assignee', models.CharField(blank=True, max_length=255, null=True)),
                ('reporter', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.CharField(blank=True, max_length=100, null=True)),
                ('updated', models.CharField(blank=True, max_length=100, null=True)),
                ('sprint', models.CharField(blank=True, max_length=255, null=True)),
                ('epic_key', models.CharField(blank=True, max_length=100, null=True)),
                ('blocks', models.JSONField(blank=True, default=list)),
                ('blocked_by', models.JSONField(blank=True, default=list)),
                ('pulled_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jira_issues', to='kanbanapp.project')),
            ],
            options={
                'ordering': ['jira_key'],
                'constraints': [models.UniqueConstraint(fields=('project', 'jira_id'), name='unique_project_jira_id')],
            },
        ),
    ]
