# Generated by Django 5.2.17 on 2026-09-28 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanbanapp', '0002_jiraissue'),
    ]

    operations = [
        migrations.AddField(
            model_name='jiraconnection',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_jira_connections', to=settings.AUTH_USER_MODEL),
        ),
    ]
