# Generated by Django 5.2.17 on 2026-09-29 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanbanapp', '0003_jiraconnection_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0)),
                ('app_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_mappings', to='kanbanapp.kanbancolumn')),
                ('jira_status', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='app_mappings', to='kanbanapp.jirastatus')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_mappings', to='kanbanapp.project')),
            ],
            options={
                'verbose_name': 'Durum Eşlemesi',
                'verbose_name_plural': 'Durum Eşlemeleri',
                'ordering': ['position', 'id'],
                'constraints': [models.UniqueConstraint(fields=('app_status',), name='unique_app_status')],
            },
        ),
    ]
