# Generated by Django 5.2.17 on 2026-09-29 08:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanbanapp', '0004_statusmapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='kanbancard',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kanbancard',
            name='developer_assessment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='kanbancard',
            name='difficulty_level',
            field=models.IntegerField(blank=True, choices=[(1, '1 - Çok Kolay'), (2, '2 - Kolay'), (3, '3 - Orta (3)'), (5, '5 - Orta (5)'), (8, '8 - Zor'), (13, '13 - Çok Zor'), (21, '21 - Aşırı Zor'), (34, '34 - Kritik (Bölünmeli)'), (55, '55 - Programcı Talebi (55)'), (89, '89 - Programcı Talebi (89)')], null=True),
        ),
        migrations.AddField(
            model_name='kanbancard',
            name='initial_difficulty_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kanbancard',
            name='is_sub_task',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kanbancard',
            name='parent_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_tasks', to='kanbanapp.kanbancard'),
        ),
        migrations.AddField(
            model_name='kanbancard',
            name='requested_difficulty_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='IssueRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('difficulty_change', 'Zorluk Değişikliği'), ('split', 'İş Bölme (Sub-task)'), ('reassign', 'Yeniden Atama')], default='difficulty_change', max_length=30)),
                ('reason', models.CharField(blank=True, choices=[('too_hard', 'Çok Zor Geldi'), ('too_easy', 'Çok Kolay Geldi')], max_length=30)),
                ('requested_difficulty', models.IntegerField(blank=True, choices=[(1, '1 - Çok Kolay'), (2, '2 - Kolay'), (3, '3 - Orta (3)'), (5, '5 - Orta (5)'), (8, '8 - Zor'), (13, '13 - Çok Zor'), (21, '21 - Aşırı Zor'), (34, '34 - Kritik (Bölünmeli)'), (55, '55 - Programcı Talebi (55)'), (89, '89 - Programcı Talebi (89)')], null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Bekliyor'), ('approved', 'Onaylandı'), ('rejected', 'Reddedildi')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_requests', to=settings.AUTH_USER_MODEL)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='kanbanapp.kanbancard')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_requests', to='kanbanapp.project')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('duration', models.CharField(choices=[('1_hafta', '1 Hafta'), ('2_hafta', '2 Hafta'), ('3_hafta', '3 Hafta'), ('4_hafta', '4 Hafta'), ('serbest', 'Serbest')], default='2_hafta', max_length=20)),
                ('status', models.CharField(choices=[('planning', 'Planlama'), ('active', 'Aktif'), ('completed', 'Tamamlandı')], default='planning', max_length=20)),
                ('position', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprints', to='kanbanapp.project')),
                ('team_members', models.ManyToManyField(blank=True, related_name='sprints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['position', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='kanbancard',
            name='sprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards', to='kanbanapp.sprint'),
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_members', to='kanbanapp.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('project', 'user'), name='unique_project_user_member')],
            },
        ),
    ]
