# Generated by Django 5.2.17 on 2026-09-29 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanbanapp', '0005_kanbancard_assignee_kanbancard_developer_assessment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jiraconnection',
            name='disable_proxy',
            field=models.BooleanField(default=True, help_text='Yerel ağ veya doğrudan bağlantılar için proxy kullanımını kapatır.', verbose_name='Proxy Devre Dışı'),
        ),
    ]
