# Generated by Django 5.2.17 on 2026-09-29 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanbanapp', '0006_jiraconnection_disable_proxy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kanbancard',
            name='column',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='kanbanapp.kanbancolumn'),
        ),
    ]
