# Generated by Django 5.2.17 on 2026-09-29 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanbanapp', '0007_alter_kanbancard_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='sync_jira_status',
            field=models.BooleanField(default=True, help_text="Kart hareketlerinde Jira üzerindeki statünün de güncellenmesini sağlar. Kapatılırsa durum Jira'ya aktarılmaz.", verbose_name='Jira Statü Aktarımı'),
        ),
        migrations.AddField(
            model_name='statusmapping',
            name='transfer_to_jira',
            field=models.BooleanField(default=True, help_text="Kart bu kolona taşındığında Jira'da ilgili statüye geçiş yapılır. Kapatılırsa bu kolon için Jira statüsü aktarılmaz.", verbose_name="Jira'ya Statü Aktar"),
        ),
    ]
