# Generated by Django 5.2.17 on 2026-09-29 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanbanapp', '0008_project_sync_jira_status_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='statusmapping',
            name='unique_app_status',
        ),
        migrations.AddField(
            model_name='statusmapping',
            name='is_primary',
            field=models.BooleanField(default=True, help_text="Kart bu kolona taşındığında Jira'da geçilecek birincil durum.", verbose_name='Birincil Geçiş Statüsü'),
        ),
        migrations.AddConstraint(
            model_name='statusmapping',
            constraint=models.UniqueConstraint(fields=('app_status', 'jira_status'), name='unique_app_jira_status'),
        ),
    ]
