# Generated by Django 5.2.17 on 2026-09-30 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanbanapp', '0009_remove_statusmapping_unique_app_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='hidden_jira_statuses',
            field=models.ManyToManyField(blank=True, help_text='Bu proje için kullanılmayan ve gizlenen Jira statüleri.', related_name='hidden_in_projects', to='kanbanapp.jirastatus', verbose_name='Gizlenen Jira Statüleri'),
        ),
    ]
