# Generated by Django 5.2.17 on 2026-10-07 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanbanapp', '0010_project_hidden_jira_statuses'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_type', models.CharField(choices=[('bug', 'Hata Bildirimi (Bug)'), ('feature', 'Yeni Geliştirme İsteği (Feature)'), ('improvement', 'İyileştirme / Revizyon')], default='bug', max_length=20)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, default='')),
                ('priority', models.CharField(choices=[('low', 'Düşük'), ('medium', 'Normal'), ('high', 'Yüksek'), ('urgent', 'Acil / Kritik')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Açık'), ('investigating', 'İnceleniyor'), ('in_progress', 'Geliştirmede'), ('resolved', 'Çözüldü'), ('closed', 'Kapatıldı'), ('rejected', 'Reddedildi')], default='open', max_length=20)),
                ('resolution_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='kanbanapp.kanbancard')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='kanbanapp.project')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hata / Talep',
                'verbose_name_plural': 'Hatalar ve Talepler',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='ticket_attachments/%Y/%m/')),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='kanbanapp.projectticket')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_ticket_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Talep Eki',
                'verbose_name_plural': 'Talep Ekleri',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='ticket_comment_attachments/%Y/%m/')),
                ('is_system_note', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_comments', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='kanbanapp.projectticket')),
            ],
            options={
                'verbose_name': 'Talep Yorumu / Mesajı',
                'verbose_name_plural': 'Talep Yorumları / Mesajları',
                'ordering': ['created_at'],
            },
        ),
    ]
