# Generated by Django 5.2.17 on 2026-10-08 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanbanapp', '0011_projectticket_ticketattachment_ticketcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectticket',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='kanbanapp.project'),
        ),
    ]
