# Generated by Django 5.2.17 on 2026-10-08 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanbanapp', '0012_alter_projectticket_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, help_text='Sprint için hedeflenen toplam kapasite / hacim puanı (boş bırakılırsa geçmiş ortalama baz alınır)', null=True, verbose_name='Kapasite (Puan)'),
        ),
    ]
