from django.urls import path

from . import views

urlpatterns = [
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("register/", views.register_view, name="register"),
    path("", views.dashboard_view, name="dashboard"),
    path("dashboard/", views.dashboard_view, name="dashboard"),
    path("projects/", views.project_list_view, name="projects"),
    path("projects/create/", views.project_create_view, name="project_create"),
    path("projects/<int:project_id>/edit/", views.project_edit_view, name="project_edit"),
    path("projects/<int:project_id>/delete/", views.project_delete_view, name="project_delete"),
    path("jira/", views.jira_connections, name="jira_connections"),
    path("jira/create/", views.jira_connection_create, name="jira_connection_create"),
    path("jira/<int:connection_id>/edit/", views.jira_connection_edit, name="jira_connection_edit"),
    path("jira/<int:connection_id>/delete/", views.jira_connection_delete, name="jira_connection_delete"),
    path("jira/<int:connection_id>/test/", views.jira_test_connection, name="jira_test_connection"),
    path("jira/<int:connection_id>/sync-statuses/", views.jira_sync_statuses, name="jira_sync_statuses"),
    path("projects/<int:project_id>/statuses/", views.project_status_mappings_view, name="project_status_mappings"),
    path("projects/<int:project_id>/sync-statuses/", views.project_jira_sync_statuses, name="project_jira_sync_statuses"),
    path("projects/<int:project_id>/refresh/", views.refresh_project, name="refresh_project"),
    path("projects/<int:project_id>/board/", views.board_view, name="board"),
    path("projects/<int:project_id>/status/create/<int:column_id>/", views.status_mapping_create_view, name="status_mapping_create"),
    path("projects/<int:project_id>/status/<int:mapping_id>/edit/", views.status_mapping_edit_view, name="status_mapping_edit"),
    path("projects/<int:project_id>/status/<int:mapping_id>/delete/", views.status_mapping_delete_view, name="status_mapping_delete"),
    path("projects/<int:project_id>/column/create/", views.kanban_column_create_view, name="kanban_column_create"),
    path("projects/<int:project_id>/column/<int:column_id>/edit/", views.kanban_column_edit_view, name="kanban_column_edit"),
    path("projects/<int:project_id>/column/<int:column_id>/delete/", views.kanban_column_delete_view, name="kanban_column_delete"),
    path("projects/<int:project_id>/card/create/", views.kanban_card_create_view, name="kanban_card_create"),
    path("projects/<int:project_id>/card/import-jira/", views.kanban_card_import_jira_view, name="kanban_card_import_jira"),
    path("projects/<int:project_id>/card/<int:card_id>/jira-refresh/", views.kanban_card_jira_refresh_view, name="kanban_card_jira_refresh"),
    path("projects/<int:project_id>/card/<int:card_id>/edit/", views.kanban_card_edit_view, name="kanban_card_edit"),
    path("projects/<int:project_id>/card/<int:card_id>/delete/", views.kanban_card_delete_view, name="kanban_card_delete"),
    path("projects/<int:project_id>/card/<int:card_id>/move/", views.kanban_card_move_view, name="kanban_card_move"),
    path("projects/<int:project_id>/cards/reorder/", views.kanban_cards_reorder_view, name="kanban_cards_reorder"),
    path("projects/<int:project_id>/columns/reorder/", views.kanban_columns_reorder_view, name="kanban_columns_reorder"),
    path("projects/<int:project_id>/card/<int:card_id>/assign/", views.kanban_card_assign_view, name="kanban_card_assign"),
    path("projects/<int:project_id>/card/<int:card_id>/request/", views.card_request_create_view, name="card_request_create"),
    path("projects/<int:project_id>/card/<int:card_id>/split/", views.card_split_view, name="card_split"),
    path("projects/<int:project_id>/requests/", views.issue_request_list_view, name="issue_requests"),
    path("projects/<int:project_id>/requests/<int:request_id>/<str:action>/", views.issue_request_action_view, name="issue_request_action"),
    path("projects/<int:project_id>/sprints/", views.sprint_list_view, name="sprints"),
    path("projects/<int:project_id>/sprints/create/", views.sprint_create_view, name="sprint_create"),
    path("projects/<int:project_id>/sprints/<int:sprint_id>/edit/", views.sprint_edit_view, name="sprint_edit"),
    path("projects/<int:project_id>/sprints/<int:sprint_id>/delete/", views.sprint_delete_view, name="sprint_delete"),
    path("projects/<int:project_id>/sprints/<int:sprint_id>/board/", views.sprint_board_view, name="sprint_board"),
    path("projects/<int:project_id>/reports/", views.report_view, name="project_reports"),
    path("projects/<int:project_id>/reports/export/", views.export_cards_csv, name="export_cards_csv"),
]
